### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Couby** [yariplus/minecraft-nodebb-integration#28]
Hi,

Still trying to get minecraft-nodebb-integration working :blush: .

Now I'm having a connexion error.

> [22:34:43 WARN]: java.net.ConnectException: Connection refused
> [22:34:43 WARN]:    at java.net.PlainSocketImpl.socketConnect(Native Method)
> [22:34:43 WARN]:    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> [22:34:43 WARN]:    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> [22:34:43 WARN]:    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> [22:34:43 WARN]:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> [22:34:43 WARN]:    at java.net.Socket.connect(Socket.java:589)
> [22:34:43 WARN]:    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
> [22:34:43 WARN]:    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
> [22:34:43 WARN]:    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
> [22:34:43 WARN]:    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
> [22:34:43 WARN]:    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
> [22:34:43 WARN]:    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
> [22:34:43 WARN]:    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
> [22:34:43 WARN]:    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
> ...

For the moment I just rout the server port. Are there any other ports or network settings required by this plugin in order to work :question: 

Regards

**Comment by yariplus** [comment]
Are you using SSL? I have not tested this without SSL.

**Comment by Couby** [comment]
Yes I'm using it on NodeBB side.
But not on Bukkit server side.

**Comment by yariplus** [comment]
Could you post the your config.yml, without the apikey and messages section?

**Comment by Couby** [comment]
Yep : 

```
forum:
  url: *https://myforumurl.com/*
  name: *MyForumName*
  apikey: *my_API_key_from_NBBForum*
socketio:
  address: *https://myforumurl.com/*
  transports:
  - polling
  - websocket
  namespace: plugins.MinecraftIntegration

```

**Comment by yariplus** [comment]
Thanks.

Does opening `https://myforumurl.com/` in the browser get properly redirected?

What CA are you using? (Let's Encrypt, StartSSL, etc..) Are you using cloudflare at all?

**Comment by Couby** [comment]
Yes the forum is working fine : https://minet4c.osezlejeu.com .

I'm using Let's Encrypt as CA.
I'm not using Cloudflare.

**Comment by yariplus** [comment]
I'm trying to reproduce the error. The only way I can make it happen so far is when the forum url is misspelled.

**Comment by Couby** [comment]
I'll check again the config.yml and will also try with volontary misspelled url to see if there is a difference on my side.
Could you share also your config.yml, without the apikey and messages section ?

**Comment by Couby** [comment]
Misspelling the url I have a different error message : 

```
[19:14:13 ERROR]: [NodeBB-Integration] Can't connect to forum at https://minet4c.osezlejeu.co/
[19:14:13 ERROR]: [NodeBB-Integration] Use `/nodebb url URL` to set the forum address.
```

Trying to set the url this way give me the following error :

```
[19:14:49 INFO]: Unknown command. Type "help" for help.
```

**Comment by yariplus** [comment]
Sure thing

```
forum:
  url: https://yaricraft.com/
  name: '&aYaricraft Forums'
  apikey: seekrit
socketio:
  address: https://ika.yaricraft.com/
  transports:
  - polling
  - websocket
  namespace: plugins.MinecraftIntegration
```

I use a different socketio address because I use cloudflare, but yours should be the same as the forum url.
